// Generated by https://quicktype.io

export interface TeamI {
    id:          number;
    createdAt:   string;
    updatedAt:   string;
    name:        string;
    slug:        string;
    description: string;
}
