// Generated by https://quicktype.io

export interface UserI {
    id:        number;
    createdAt: string;
    updatedAt: string;
    firstName: string;
    lastName:  string;
    email:     string;
}
