// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface UserI {
    id:                  number;
    createdAt:           string;
    updatedAt:           string;
    firstName:           string;
    lastName:            string;
    email:               string;
    workflowsToManagers: WorkflowsToManager[];
    teamsToUsers:        any[];
}

export interface WorkflowsToManager {
    id:        number;
    createdAt: string;
    updatedAt: string;
    isCreator: boolean;
    workflow:  Workflow;
}

export interface Workflow {
    id:          number;
    createdAt:   string;
    updatedAt:   string;
    title:       string;
    slug:        string;
    description: null;
}
