// Generated by https://quicktype.io

import { ProjectI } from './project.interface';

export interface WorkflowI {
    id: number;
    createdAt: string;
    updatedAt: string;
    title: string;
    slug: string;
    description: null;
    projects: ProjectI[];
}
