// Generated by https://quicktype.io

export interface WorkflowI {
    id:          number;
    createdAt:   string;
    updatedAt:   string;
    title:       string;
    slug:        string;
    description: null;
}
